# A simple way to download financial data from Investing.com in Python

## Setup

In [1]:
import investpy as inv

## Stocks data

In [2]:
inv.get_stocks_overview(country="United States", 
                        as_json=False, 
                        n_results=1000)

,country,name,symbol,last,high,low,change,change_percentage,turnover,currency
0,united states,Boeing,BA,223.57,228.66,223.12,-2.88,-1.27%,8430000,USD
1,united states,General Motors,GM,58.96,59.33,57.86,+0.87,+1.50%,17030000,USD
2,united states,Chevron,CVX,107.15,107.58,106.17,+0.02,+0.02%,8740000,USD
3,united states,Citigroup,C,70.64,71.94,70.43,-1.04,-1.45%,17560000,USD
4,united states,Bank of America,BAC,43.54,44.00,43.27,-0.24,-0.55%,36800000,USD
...,...,...,...,...,...,...,...,...,...,...
995,united states,Female Health,VERU,8.49,8.57,8.40,+0.070,+0.83%,181740,USD
996,united states,First Interstate BancSystem,FIBK,41.95,42.16,41.22,+0.20,+0.48%,518010,USD
997,united states,Financial Institutions,FISI,31.50,31.60,31.03,+0.30,+0.96%,23480,USD
998,united states,National Beverage,FIZZ,54.90,55.75,54.59,-0.03,-0.05%,227580,USD
999,united states,Fluidigm,FLDM,5.35,5.47,5.32,+0.010,+0.19%,356330,USD

In [3]:
TICKER = "AAPL"

In [4]:
inv.get_stock_company_profile(stock=TICKER, country="United States")

{'url': 'https://www.investing.com/equities/apple-computer-inc-company-profile',
 'desc': 'Apple Inc. designs, manufactures and markets smartphones, personal computers, tablets, wearables and accessories, and sells a variety of related services. The Company’s products include iPhone, Mac, iPad, and Wearables, Home and Accessories. iPhone is the Company’s line of smartphones based on its iOS operating system. Mac is the Company’s line of personal computers based on its macOS operating system. iPad is the Company’s line of multi-purpose tablets based on its iPadOS operating system. Wearables, Home and Accessories includes AirPods, Apple TV, Apple Watch, Beats products, HomePod, iPod touch and other Apple-branded and third-party accessories. AirPods are the Company’s wireless headphones that interact with Siri. Apple Watch is the Company’s line of smart watches. Its services include Advertising, AppleCare, Cloud Services, Digital Content and Payment Services. Its customers are primarily in the consumer, small and mid-sized business, education, enterprise and government markets.'}

In [5]:
inv.get_stock_financial_summary(stock=TICKER,
                                country="United States",
                                summary_type="income_statement", 
                                period="quarterly")

            Total Revenue  Gross Profit  Operating Income  Net Income
Date
2021-06-26        81434.0       35255.0           24126.0     21744.0
2021-03-27        89584.0       38079.0           27503.0     23630.0
2020-12-26       111439.0       44328.0           33534.0     28755.0
2020-09-26        64698.0       24689.0           14775.0     12673.0

In [6]:
inv.get_stock_information(stock=TICKER,
                          country="United States",
                          as_json=False).transpose()

                                  0
Stock Symbol                   AAPL
Prev. Close                  142.81
Todays Range          141.04-143.25
Revenue              347160000000.0
Open                         143.23
52 wk Range           107.32-157.26
EPS                            5.11
Volume                   71242361.0
Market Cap          2360000000000.0
Dividend (Yield)        0.88(0.62%)
Average Vol. (3m)        78909778.0
P/E Ratio                     27.97
Beta                           1.23
1-Year Change                22.09%
Shares Outstanding    16530166000.0
Next Earnings Date       28/10/2021

In [7]:
df = inv.get_stock_historical_data(stock=TICKER,
                                   country="United States",
                                   from_date="01/01/2020",
                                   to_date="01/01/2021")
df

              Open    High     Low   Close     Volume Currency
Date
2020-01-02   74.06   75.15   73.80   75.09  135647008      USD
2020-01-03   74.29   75.14   74.13   74.36  146536000      USD
2020-01-06   73.45   74.99   73.19   74.95  118579000      USD
2020-01-07   74.96   75.22   74.37   74.60  111511000      USD
2020-01-08   74.29   76.11   74.29   75.80  132364000      USD
...            ...     ...     ...     ...        ...      ...
2020-12-24  131.32  133.46  131.10  131.97   54930000      USD
2020-12-28  133.99  137.34  133.51  136.69  124486000      USD
2020-12-29  138.05  138.79  134.34  134.87  121047000      USD
2020-12-30  135.58  135.99  133.40  133.72   96452000      USD
2020-12-31  134.08  134.74  131.72  132.69   99117000      USD

[253 rows x 6 columns]

In [8]:
aapl = inv.search_quotes(text="apple", 
                         products=["stocks"],
                         countries=["united states"], 
                         n_results=1)
print(aapl)

{"id_": 6408, "name": "Apple Inc", "symbol": "AAPL", "country": "united states", "tag": "/equities/apple-computer-inc", "pair_type": "stocks", "exchange": "NASDAQ"}

In [9]:
recent_data = aapl.retrieve_recent_data()
recent_data

              Open    High     Low   Close     Volume  Change Pct
Date
2021-09-13  150.63  151.42  148.75  149.55   97785000        0.39
2021-09-14  150.35  151.07  146.91  148.12  108412000       -0.96
2021-09-15  148.56  149.44  146.37  149.03   81631000        0.61
2021-09-16  148.44  148.97  147.22  148.79   67882000       -0.16
2021-09-17  148.82  148.82  145.76  146.06  129869000       -1.83
2021-09-20  143.80  144.84  141.27  142.94  123040000       -2.14
2021-09-21  143.93  144.60  142.78  143.43   75168000        0.34
2021-09-22  144.45  146.43  143.70  145.85   76404000        1.69
2021-09-23  146.65  147.08  145.64  146.83   64513000        0.67
2021-09-24  145.66  147.47  145.56  146.92   53478000        0.06
2021-09-27  145.47  145.96  143.82  145.37   72233000       -1.05
2021-09-28  143.25  144.75  141.69  141.91  108445000       -2.38
2021-09-29  142.47  144.45  142.03  142.83   74300000        0.65
2021-09-30  143.66  144.38  141.28  141.50   88768000       -0.93
2021-10-01  141.90  142.92  139.11  142.65   94640000        0.81
2021-10-04  141.76  142.21  138.27  139.14   97904000       -2.46
2021-10-05  139.49  142.24  139.36  141.11   80575000        1.42
2021-10-06  139.47  142.15  138.37  142.00   82622000        0.63
2021-10-07  143.06  144.21  142.72  143.29   61406000        0.91
2021-10-08  144.03  144.18  142.56  142.90   58773000       -0.27
2021-10-11  142.27  144.81  141.81  142.81   64255000       -0.06
2021-10-12  143.13  143.14  141.19  141.51   71242360       -0.91

In [10]:
historical_data = aapl.retrieve_historical_data(from_date="01/01/2020", 
                                                to_date="01/01/2021")
historical_data

              Open    High     Low   Close     Volume  Change Pct
Date
2020-01-02   74.06   75.15   73.80   75.09  135647008        2.28
2020-01-03   74.29   75.14   74.13   74.36  146536000       -0.97
2020-01-06   73.45   74.99   73.19   74.95  118579000        0.80
2020-01-07   74.96   75.22   74.37   74.60  111511000       -0.47
2020-01-08   74.29   76.11   74.29   75.80  132364000        1.61
...            ...     ...     ...     ...        ...         ...
2020-12-24  131.32  133.46  131.10  131.97   54930000        0.77
2020-12-28  133.99  137.34  133.51  136.69  124486000        3.58
2020-12-29  138.05  138.79  134.34  134.87  121047000       -1.33
2020-12-30  135.58  135.99  133.40  133.72   96452000       -0.85
2020-12-31  134.08  134.74  131.72  132.69   99117000       -0.77

[253 rows x 6 columns]

In [11]:
aapl.retrieve_technical_indicators(interval="daily")

              indicator           signal    value
0               RSI(14)             sell  41.2500
1            STOCH(9,6)          neutral  54.2550
2          STOCHRSI(14)              buy  56.8060
3           MACD(12,26)             sell  -1.7000
4               ADX(14)             sell  33.5450
5           Williams %R             sell -65.4350
6               CCI(14)             sell -56.1727
7               ATR(14)  less_volatility   2.8301
8        Highs/Lows(14)             sell  -0.2222
9   Ultimate Oscillator             sell  46.1370
10                  ROC             sell  -3.0170
11  Bull/Bear Power(13)             sell  -1.8700

In [12]:
aapl.retrieve_technical_indicators(interval="weekly")

              indicator           signal     value
0               RSI(14)          neutral   52.1590
1            STOCH(9,6)             sell   34.5180
2          STOCHRSI(14)         oversold    0.0000
3           MACD(12,26)              buy    3.2400
4               ADX(14)              buy   46.6500
5           Williams %R         oversold  -83.2540
6               CCI(14)             sell -123.2443
7               ATR(14)  less_volatility    5.9353
8        Highs/Lows(14)             sell   -2.3043
9   Ultimate Oscillator          neutral   49.7940
10                  ROC             sell   -2.5220
11  Bull/Bear Power(13)             sell   -1.4920

## Crypto data

In [13]:
inv.search_cryptos(by="name", value="doge")

                      name    symbol currency       status
0                 Dogecoin      DOGE      USD    available
1                 LiteDoge     LDOGE      USD    available
2                 DogeCash     DOGEC           unavailable
3               Doge Token     DOGET           unavailable
4                 Dogeswap     DOGES           unavailable
5                   DOGEFI    DOGEFI           unavailable
6                  renDOGE   RENDOGE           unavailable
7                DogeYield      DOGY           unavailable
8   3X Long Dogecoin Token  DOGEBULL           unavailable
9  3X Short Dogecoin Token  DOGEBEAR           unavailable

In [14]:
df = inv.get_crypto_historical_data(crypto="Dogecoin",
                                    from_date="01/01/2020",
                                    to_date="11/01/2020")
df

                Open      High       Low     Close      Volume Currency
Date
2020-01-01  0.002015  0.002056  0.002004  0.002040  1438402432      USD
2020-01-02  0.002040  0.002051  0.001991  0.001999  1863567232      USD
2020-01-03  0.001999  0.002265  0.001989  0.002042  1693032448      USD
2020-01-04  0.002042  0.002318  0.002041  0.002307  1545883008      USD
2020-01-05  0.002307  0.002336  0.002076  0.002080  1568643072      USD
2020-01-06  0.002080  0.002249  0.002078  0.002153  1663263232      USD
2020-01-07  0.002153  0.002319  0.002137  0.002182  1749696128      USD
2020-01-08  0.002182  0.002234  0.002126  0.002138  1843089408      USD
2020-01-09  0.002138  0.002207  0.002105  0.002138  1639263232      USD
2020-01-10  0.002138  0.002209  0.002090  0.002208  1708077568      USD
2020-01-11  0.002207  0.002240  0.002164  0.002179  1731039488      USD

In [15]:
search_result = inv.search_quotes(text="doge", 
                                  products=["cryptos"],
                                  n_results=100)
for res in search_result:
    print(res)

{"id_": 1158819, "name": "Dogecoin US Dollar", "symbol": "DOGE/USD", "country": null, "tag": "/crypto/dogecoin/doge-usd", "pair_type": "cryptos", "exchange": "Binance"}
{"id_": 1159391, "name": "PeepCoin Dogecoin", "symbol": "PCN/DOGE", "country": null, "tag": "/crypto/peepcoin/pcn-doge", "pair_type": "cryptos", "exchange": "C-Patex"}
{"id_": 1138482, "name": "AsiaCoin Dogecoin", "symbol": "AC/DOGE", "country": null, "tag": "/crypto/asiacoin/ac-doge", "pair_type": "cryptos", "exchange": "Nova Exchange"}
{"id_": 1153037, "name": "ParallelCoin Dogecoin", "symbol": "DUO/DOGE", "country": null, "tag": "/crypto/parallelcoin/duo-doge", "pair_type": "cryptos", "exchange": "YoBit"}
{"id_": 1155935, "name": "Zeitcoin Dogecoin", "symbol": "ZEIT/DOGE", "country": null, "tag": "/crypto/zeitcoin/zeit-doge", "pair_type": "cryptos", "exchange": "SouthXchange"}
{"id_": 1156066, "name": "PAC Global Dogecoin", "symbol": "PAC/DOGE", "country": null, "tag": "/crypto/pac-global/pac-doge", "pair_type": "cryptos", "exchange": "Graviex"}
{"id_": 1156221, "name": "Dogecoin Chinese Yuan", "symbol": "DOGE/CNY", "country": null, "tag": "/crypto/dogecoin/doge-cny", "pair_type": "cryptos", "exchange": "Synthetic"}
{"id_": 1156546, "name": "TEKcoin Dogecoin", "symbol": "TEK/DOGE", "country": null, "tag": "/crypto/tekcoin/tek-doge", "pair_type": "cryptos", "exchange": "YoBit"}
{"id_": 1164151, "name": "GCN Coin Dogecoin", "symbol": "GCN/DOGE", "country": null, "tag": "/crypto/gcn-coin/gcn-doge", "pair_type": "cryptos", "exchange": "SouthXchange"}
{"id_": 1136042, "name": "Nano Dogecoin", "symbol": "NANO/DOGE", "country": null, "tag": "/crypto/nano/nano-doge", "pair_type": "cryptos", "exchange": "Mercatox"}
{"id_": 1167165, "name": "Dogecoin Bitcoin", "symbol": "DOGE/BTC", "country": null, "tag": "/crypto/dogecoin/doge-btc", "pair_type": "cryptos", "exchange": "Binance"}
{"id_": 1169563, "name": "Dogecoin Euro", "symbol": "DOGE/EUR", "country": null, "tag": "/crypto/dogecoin/doge-eur", "pair_type": "cryptos", "exchange": "Binance"}
{"id_": 1173192, "name": "Dogecoin Canadian Dollar", "symbol": "DOGE/CAD", "country": null, "tag": "/crypto/dogecoin/doge-cad", "pair_type": "cryptos", "exchange": "Synthetic"}
{"id_": 1173204, "name": "Dogecoin Binance USD", "symbol": "DOGE/BUSD", "country": null, "tag": "/crypto/dogecoin/doge-busd", "pair_type": "cryptos", "exchange": "Binance"}
{"id_": 1173205, "name": "Dogecoin Russian Ruble", "symbol": "DOGE/RUB", "country": null, "tag": "/crypto/dogecoin/doge-rub", "pair_type": "cryptos", "exchange": "Binance"}
{"id_": 1173408, "name": "Dogecoin Korean Won", "symbol": "DOGE/KRW", "country": null, "tag": "/crypto/dogecoin/doge-krw", "pair_type": "cryptos", "exchange": "Bithumb"}
{"id_": 1174716, "name": "Dogecoin Australian Dollar", "symbol": "DOGE/AUD", "country": null, "tag": "/crypto/dogecoin/doge-aud", "pair_type": "cryptos", "exchange": "Binance"}
{"id_": 1175364, "name": "Dogecoin Indian Rupee", "symbol": "DOGE/INR", "country": null, "tag": "/crypto/dogecoin/doge-inr", "pair_type": "cryptos", "exchange": "Bitbns"}
{"id_": 1138339, "name": "Atomic Coin Dogecoin", "symbol": "ATOMc/DOGE", "country": null, "tag": "/crypto/atomic-coin/atom-doge", "pair_type": "cryptos", "exchange": "Nova Exchange"}
{"id_": 1156052, "name": "OP Coin Dogecoin", "symbol": "OPC/DOGE", "country": null, "tag": "/crypto/op-coin/opc-doge", "pair_type": "cryptos", "exchange": "Trade Satoshi"}
{"id_": 1135974, "name": "Dogecoin Litecoin", "symbol": "DOGE/LTC", "country": null, "tag": "/crypto/dogecoin/doge-ltc", "pair_type": "cryptos", "exchange": "STEX"}
{"id_": 1063960, "name": "Sprouts Dogecoin", "symbol": "SPRTS/DOGE", "country": null, "tag": "/crypto/sprouts/sprts-doge", "pair_type": "cryptos", "exchange": "CoinExchange"}
{"id_": 1056789, "name": "Dogecoin Ethereum", "symbol": "DOGE/ETH", "country": null, "tag": "/crypto/dogecoin/doge-eth", "pair_type": "cryptos", "exchange": "HitBTC"}
{"id_": 1058464, "name": "808Coin Dogecoin", "symbol": "808/DOGE", "country": null, "tag": "/crypto/808coin/808-doge", "pair_type": "cryptos", "exchange": "Cryptopia"}
{"id_": 1058566, "name": "Bongger Dogecoin", "symbol": "BGR/DOGE", "country": null, "tag": "/crypto/bongger/bgr-doge", "pair_type": "cryptos", "exchange": "Cryptopia"}
{"id_": 1128860, "name": "Dogecoin Turkish Lira", "symbol": "DOGE/TRY", "country": null, "tag": "/crypto/dogecoin/doge-try", "pair_type": "cryptos", "exchange": "Paribu"}
{"id_": 1058941, "name": "The Cypherfunks Dogecoin", "symbol": "FUNK/DOGE", "country": null, "tag": "/crypto/the-cypherfunks/funk-doge", "pair_type": "cryptos", "exchange": "Cryptopia"}
{"id_": 1059125, "name": "LottoCoin Dogecoin", "symbol": "LOT/DOGE", "country": null, "tag": "/crypto/lottocoin/lot-doge", "pair_type": "cryptos", "exchange": "Cryptopia"}
{"id_": 1059239, "name": "IncaKoin Dogecoin", "symbol": "NKA/DOGE", "country": null, "tag": "/crypto/incakoin/nka-doge", "pair_type": "cryptos", "exchange": "Cryptopia"}
{"id_": 1059738, "name": "Royalties Dogecoin", "symbol": "XRY/DOGE", "country": null, "tag": "/crypto/royalties/xry-doge", "pair_type": "cryptos", "exchange": "Cryptopia"}
{"id_": 1058586, "name": "BlazeCoin Dogecoin", "symbol": "BLZ/DOGE", "country": null, "tag": "/crypto/blazecoin/blz-doge", "pair_type": "cryptos", "exchange": "Cryptopia"}
{"id_": 1064336, "name": "FuturoCoin Dogecoin", "symbol": "FTO/DOGE", "country": null, "tag": "/crypto/futurocoin/fto-doge", "pair_type": "cryptos", "exchange": "YoBit"}
{"id_": 1072975, "name": "Prime-Ex Perpetual Dogecoin", "symbol": "PEXT/DOGE", "country": null, "tag": "/crypto/prime-ex-perpetual/pext-doge", "pair_type": "cryptos", "exchange": "YoBit"}
{"id_": 1077181, "name": "Slothcoin Dogecoin", "symbol": "SLOTH/DOGE", "country": null, "tag": "/crypto/slothcoin/sloth-doge", "pair_type": "cryptos", "exchange": "Cryptopia"}
{"id_": 1080133, "name": "LockTrip Dogecoin", "symbol": "LOC/DOGE", "country": null, "tag": "/crypto/lockchain/loc-doge", "pair_type": "cryptos", "exchange": "YoBit"}
{"id_": 1096085, "name": "Dogecoin Brazil Real", "symbol": "DOGE/BRL", "country": null, "tag": "/crypto/dogecoin/doge-brl", "pair_type": "cryptos", "exchange": "Coingecko"}
{"id_": 1097944, "name": "Bitcoin SV Dogecoin", "symbol": "BCHSV/DOGE", "country": null, "tag": "/crypto/bitcoin-sv/bchsv-doge", "pair_type": "cryptos", "exchange": "YoBit"}
{"id_": 1127864, "name": "Gapcoin Dogecoin", "symbol": "GAP/DOGE", "country": null, "tag": "/crypto/gapcoin/gap-doge", "pair_type": "cryptos", "exchange": "Nova Exchange"}
{"id_": 1066582, "name": "CryCash Dogecoin", "symbol": "CRCA/DOGE", "country": null, "tag": "/crypto/crycash/crca-doge", "pair_type": "cryptos", "exchange": "YoBit"}
{"id_": 1173841, "name": "Dogecoin US Dollar", "symbol": "DOGE/USD", "country": null, "tag": "/crypto/dogecoin/doge-usd?cid=1173841", "pair_type": "cryptos", "exchange": "Coinbase Pro"}
{"id_": 1176588, "name": "Dogecoin Korean Won", "symbol": "DOGE/KRW", "country": null, "tag": "/crypto/dogecoin/doge-krw?cid=1176588", "pair_type": "cryptos", "exchange": "Upbit"}
{"id_": 1173843, "name": "Dogecoin Euro", "symbol": "DOGE/EUR", "country": null, "tag": "/crypto/dogecoin/doge-eur?cid=1173843", "pair_type": "cryptos", "exchange": "Coinbase Pro"}
{"id_": 1173842, "name": "Dogecoin Bitcoin", "symbol": "DOGE/BTC", "country": null, "tag": "/crypto/dogecoin/doge-btc?cid=1173842", "pair_type": "cryptos", "exchange": "Coinbase Pro"}
{"id_": 1128793, "name": "Dogecoin US Dollar", "symbol": "DOGE/USD", "country": null, "tag": "/crypto/dogecoin/doge-usd?cid=1128793", "pair_type": "cryptos", "exchange": "ZB.COM"}
{"id_": 1173208, "name": "Dogecoin Turkish Lira", "symbol": "DOGE/TRY", "country": null, "tag": "/crypto/dogecoin/doge-try?cid=1173208", "pair_type": "cryptos", "exchange": "Binance"}
{"id_": 1170215, "name": "Dogecoin Euro", "symbol": "DOGE/EUR", "country": null, "tag": "/crypto/dogecoin/doge-eur?cid=1170215", "pair_type": "cryptos", "exchange": "Kraken"}
{"id_": 1128790, "name": "Dogecoin Ethereum", "symbol": "DOGE/ETH", "country": null, "tag": "/crypto/dogecoin/doge-eth?cid=1128790", "pair_type": "cryptos", "exchange": "Huobi"}
{"id_": 1128789, "name": "Dogecoin US Dollar", "symbol": "DOGE/USD", "country": null, "tag": "/crypto/dogecoin/doge-usd?cid=1128789", "pair_type": "cryptos", "exchange": "Huobi"}

## Bond data

In [16]:
inv.get_bond_historical_data(bond="Netherlands 10Y", 
                             from_date="01/01/2020", 
                             to_date="01/12/2020")

             Open   High    Low  Close
Date
2020-01-02 -0.041 -0.031 -0.110 -0.095
2020-01-03 -0.139 -0.132 -0.172 -0.156
2020-01-06 -0.168 -0.151 -0.181 -0.155
2020-01-07 -0.152 -0.141 -0.168 -0.154
2020-01-08 -0.167 -0.119 -0.170 -0.122
...           ...    ...    ...    ...
2020-11-25 -0.477 -0.465 -0.498 -0.484
2020-11-26 -0.479 -0.472 -0.506 -0.501
2020-11-27 -0.500 -0.491 -0.511 -0.502
2020-11-30 -0.501 -0.480 -0.516 -0.482
2020-12-01 -0.492 -0.434 -0.498 -0.438

[248 rows x 4 columns]

## Economic calendar

In [17]:
inv.economic_calendar()

,id,date,time,zone,currency,importance,event,actual,forecast,previous
0,215,12/10/2021,All Day,venezuela,None,None,Venezuela - Public Holiday,None,None,None
1,225,12/10/2021,All Day,brazil,None,None,Brazil - Our Lady of Aparecida Day,None,None,None
2,437254,12/10/2021,00:45,new zealand,NZD,medium,Electronic Card Retail Sales (MoM) (Sep),0.9%,None,-19.7%
3,437252,12/10/2021,00:45,new zealand,NZD,low,Electronic Card Retail Sales (YoY) (Sep),-14.9%,None,-11.4%
4,437253,12/10/2021,00:45,new zealand,NZD,low,External Migration & Visitors (Aug),-44.00%,None,767.80%
...,...,...,...,...,...,...,...,...,...,...
64,438629,12/10/2021,19:30,united states,USD,medium,FOMC Member Bostic Speaks,None,None,None
65,438350,12/10/2021,20:00,united states,USD,medium,10-Year Note Auction,1.584%,None,1.338%
66,438332,12/10/2021,20:00,united states,USD,low,3-Month Bill Auction,0.050%,None,0.040%
67,215,12/10/2021,All Day,venezuela,None,None,Venezuela - Public Holiday,None,None,None
68,225,12/10/2021,All Day,brazil,None,None,Brazil - Our Lady of Aparecida Day,None,None,None

In [18]:
calendar_2020 = inv.economic_calendar(from_date="01/01/2020", 
                                      to_date="31/01/2020")
calendar_2020.query("importance == 'high'")

,id,date,time,zone,currency,importance,event,actual,forecast,previous
121,398314,02/01/2020,04:45,china,CNY,high,Caixin Manufacturing PMI (Dec),51.5,51.8,51.8
142,398331,02/01/2020,11:55,germany,EUR,high,German Manufacturing PMI (Dec),43.7,43.4,43.4
145,398336,02/01/2020,12:30,united kingdom,GBP,high,Manufacturing PMI (Dec),47.5,47.6,48.9
155,399117,02/01/2020,16:30,united states,USD,high,Initial Jobless Claims,222K,225K,224K
191,398422,03/01/2020,11:55,germany,EUR,high,German Unemployment Change (Dec),8K,2K,-16K
...,...,...,...,...,...,...,...,...,...,...
2643,399712,30/01/2020,16:30,united states,USD,high,GDP (QoQ) (Q4),2.1%,2.1%,2.1%
2646,400699,30/01/2020,16:30,united states,USD,high,Initial Jobless Claims,216K,215K,223K
2679,399818,31/01/2020,04:00,china,CNY,high,Manufacturing PMI (Jan),50.0,50.0,50.2
2739,399854,31/01/2020,13:00,euro zone,EUR,high,CPI (YoY) (Jan),1.4%,1.4%,1.3%
2949,399886,31/01/2020,16:30,canada,CAD,high,GDP (MoM) (Nov),0.1%,0.1%,-0.1%